import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import storybook from 'eslint-plugin-storybook'
import unusedImports from 'eslint-plugin-unused-imports'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

/**
 * ESLint flat config (v9+).
 *
 * Order matters: Prettier config (`eslint-config-prettier`) MUST come last
 * so it can turn off any stylistic rules that would fight with `prettier`.
 * We don't include `eslint-plugin-prettier` — running prettier separately
 * from lint (via lint-staged) is faster and keeps error messages cleaner.
 */
export default [
  // Global ignores — applies to every following config block.
  {
    ignores: [
      'dist/**',
      'storybook-static/**',
      'node_modules/**',
      '.claude/**',
      // `.tamagui/` is auto-generated by Tamagui's build pipeline (compiled
      // config + prebuilt components). Never hand-edited, never linted.
      '.tamagui/**',
      '*.tsbuildinfo',
    ],
  },

  // Base JS + TypeScript recommended rules.
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // React + hooks + a11y for all TS/JS source files.
  {
    files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2024,
      },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
      'unused-imports': unusedImports,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      // ---- React ----
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules, // React 17+ new JSX transform
      'react/prop-types': 'off', // We use TypeScript for prop validation.
      'react/react-in-jsx-scope': 'off', // Not needed with new JSX transform.
      'react/no-unescaped-entities': 'off', // Apostrophes in prose are fine.
      'react/display-name': 'off', // forwardRef components set name via function name.

      // ---- React Hooks ----
      ...reactHooks.configs.recommended.rules,
      'react-hooks/exhaustive-deps': 'warn', // Warn, don't error — often noisy in stories.

      // ---- Accessibility ----
      ...jsxA11y.configs.recommended.rules,
      // Tamagui components render as native views on RN — some of these are
      // web-specific concepts that don't map cleanly. Downgrade to warn so
      // they surface without blocking the build.
      'jsx-a11y/no-static-element-interactions': 'warn',
      'jsx-a11y/click-events-have-key-events': 'warn',

      // ---- Unused imports (auto-fixable) ----
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
        },
      ],
      // Disable base rule; the unused-imports plugin covers it with the
      // underscore-ignore pattern we actually want.
      '@typescript-eslint/no-unused-vars': 'off',

      // ---- TypeScript ----
      // We use `as never` / `as any` in a few places to work around Tamagui
      // internal typing gaps — surface these as warn, not error.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/ban-ts-comment': [
        'warn',
        { 'ts-expect-error': 'allow-with-description' },
      ],
      // Empty object type is fine for extending interfaces.
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },

  // Storybook-specific rules for *.stories.tsx.
  ...storybook.configs['flat/recommended'],

  // Storybook config files (main.ts, preview.tsx, manager.ts) have their own
  // valid patterns — relax a couple of rules that would false-positive.
  {
    files: ['.storybook/**/*.{ts,tsx,js,jsx}'],
    rules: {
      'import/no-anonymous-default-export': 'off',
    },
  },

  // Prettier compatibility — must be LAST so its rule overrides win.
  prettier,
]
